/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Nihilai Collective Corp
 * https://github.com/nihilai-collective/json-performance
 * include/tests.hpp
 */

#pragma once

#include <common.hpp>

namespace tests {

	static constexpr benchmarksuite::string_literal stage_name{ "Json-Performance: Correctness Validation" };

	std::string make_commit_row(std::string_view label, std::string_view org_repo, std::string_view commit) {
		std::string result;
		result.reserve(99);
		result += "| ";
		result += label;
		result += ": [";
		result += commit;
		result += "](https://github.com/";
		result += org_repo;
		result += "/commit/";
		result += commit;
		result += ")  \n";
		return result;
	}

	std::string make_section00() {
		std::string result;
		result.reserve(164);
		result += "# Json-Performance\nPerformance profiling of JSON libraries (Compiled and run on ";
		result += benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::os_id;
		result += " ";
		result += benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::os_version;
		result += " using the ";
		result += benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::compiler_id;
		result += " ";
		result += benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::compiler_version;
		result += " compiler).  \n\nLatest Results: (";
		return result;
	}

	std::string make_section01() {
		std::string result;
		result.reserve(227);
		result += "#### Using the following commits:\n----\n";
		result += make_commit_row("Jsonifier", "nihilai-collective/Jsonifier", JSONIFIER_COMMIT);
		result += make_commit_row("Simdjson (On Demand)", "nihilai-collective/simdjson", SIMDJSON_COMMIT);
		return result;
	}

	std::string make_section02() {
		std::string result;
		result.reserve(459);
		result += "\n#### Active Implementations:\n";
		result += "| Library | Active Implementation |\n";
		result += "| ------- | --------------------- |\n";
		result += "| Jsonifier | `";
		result += jsonifier::cpu_arch_name;
		result += "` |\n";
		result += "| simdjson (ondemand) | `";
		result += simdjson::get_active_implementation()->name();
		result += "` |\n";
		result += "\n>> In these tests, we are comparing the 'json structural tape' generated by each of the libraries during their 'stage-1' parsing. You can view the branch "
				  "that was created on the simdjson repo to facilitate this comparison "
				  "[here](https://github.com/nihilai-collective/simdjson/commit/7002cd32).  \n\n";
		return result;
	}

	struct comparison_context {
		std::vector<uint32_t> indices{};

		comparison_context() {
			indices.reserve(4096);
		}
	};

	struct element_comparison_result {
		bool matched{ true };
		size_t structural_count{};
		std::string failure_message{};
	};

	element_comparison_result compare_element(std::string_view test_str, const std::string& json_data_in) {
		element_comparison_result result{};
		comparison_context jsonifier_context{};
		jsonifier::jsonifier_core<> jsonifier_parser{};
		jsonifier_parser.parseJsonForComparison<jsonifier::parse_options{ .partialRead = true }>(jsonifier_context, json_data_in);

		comparison_context simdjson_context{};
		simdjson::ondemand::parser simdjson_parser{};
		simdjson_parser.iterate_for_comparison(simdjson_context, simdjson::padded_string_view{ json_data_in });

		if (jsonifier_context.indices.size() != simdjson_context.indices.size()) {
			std::cerr << "Count mismatch for " << test_str << ": Jsonifier=" << jsonifier_context.indices.size() << ", Simdjson=" << simdjson_context.indices.size() << std::endl;
			result.matched		   = false;
			result.failure_message = "**MISMATCH:** Jsonifier produced " + std::to_string(jsonifier_context.indices.size()) + " structurals, Simdjson produced " +
				std::to_string(simdjson_context.indices.size()) + ".\n\n";
			return result;
		}

		auto [j_it, s_it] = std::mismatch(jsonifier_context.indices.begin(), jsonifier_context.indices.end(), simdjson_context.indices.begin());
		if (j_it != jsonifier_context.indices.end()) {
			auto idx = std::distance(jsonifier_context.indices.begin(), j_it);
			std::cerr << "Structural index mismatch in " << test_str << " at tape index " << idx << " (Jsonifier=" << *j_it << ", Simdjson=" << *s_it << ")" << std::endl;
			result.matched		   = false;
			result.failure_message = "**MISMATCH:** Value divergence starting at index " + std::to_string(idx) + ". ❌\n\n";
			return result;
		}

		result.structural_count = jsonifier_context.indices.size();
		return result;
	}

	template<benchmarksuite::string_literal test_name, bool is_pod> bool execute_test(std::string& newer_string) {
		static constexpr std::string_view test_str{ test_name };
		std::string full_path;
		full_path.reserve(json_path.size() + 1 + test_str.size() + 5);
		full_path += std::string_view{ json_path };
		full_path += "/";
		full_path += test_str;
		full_path += ".json";
		auto raw_data = benchmarksuite::file_handle::get(full_path);

		std::vector<std::string> json_elements;
		if constexpr (is_pod) {
			json_elements = string_to_vector(raw_data);
		} else {
			json_elements.emplace_back(std::move(raw_data));
		}

		newer_string += "\n----\n### ";
		newer_string += test_str;
		newer_string += " Structural Comparison\n\n";

		size_t total_structurals{};
		for (size_t x = 0; x < json_elements.size(); ++x) {
			auto result = compare_element(test_str, json_elements[x]);
			if (!result.matched) {
				if constexpr (is_pod) {
					newer_string += "Element ";
					newer_string += std::to_string(x);
					newer_string += " of ";
					newer_string += std::to_string(json_elements.size());
					newer_string += ": ";
				}
				newer_string += result.failure_message;
				return false;
			}
			total_structurals += result.structural_count;
		}

		std::cout << "All " << total_structurals << " structurals match for test: " << test_str << std::endl;
		newer_string += "All **";
		newer_string += std::to_string(total_structurals);
		newer_string += "** structurals";
		if constexpr (is_pod) {
			newer_string += " across **";
			newer_string += std::to_string(json_elements.size());
			newer_string += "** elements";
		}
		newer_string += " match between Jsonifier and Simdjson. ✅\n\n";
		return true;
	}

	template<benchmarksuite::string_literal test_name, bool is_pod> bool execute_test_pair(std::string& newer_string) {
		if constexpr (is_pod) {
			return execute_test<test_name, true>(newer_string);
		} else {
			bool passed{ execute_test<test_name + " (Minified)", false>(newer_string) };
			passed &= execute_test<test_name + " (Prettified)", false>(newer_string);
			return passed;
		}
	}

	int32_t test_function() {
		std::string newer_string;
		newer_string.reserve(16384);

		newer_string += make_section00();
		newer_string += benchmarksuite::get_time();
		newer_string += ")\n";
		newer_string += make_section01();
		newer_string += make_section02();

		bool all_passed = true;
		all_passed &= execute_test_pair<"Bool Test", true>(newer_string);
		all_passed &= execute_test_pair<"Double Test", true>(newer_string);
		all_passed &= execute_test_pair<"Int64 Test", true>(newer_string);
		all_passed &= execute_test_pair<"String Test", true>(newer_string);
		all_passed &= execute_test_pair<"Uint64 Test", true>(newer_string);
		all_passed &= execute_test_pair<"Canada Test", false>(newer_string);
		all_passed &= execute_test_pair<"CitmCatalog Test", false>(newer_string);
		all_passed &= execute_test_pair<"Discord Test", false>(newer_string);
		all_passed &= execute_test_pair<"Google Maps Response Test", false>(newer_string);
		all_passed &= execute_test_pair<"Instruments Test", false>(newer_string);
		all_passed &= execute_test_pair<"Marine IK Test", false>(newer_string);
		all_passed &= execute_test_pair<"Mesh Test", false>(newer_string);
		all_passed &= execute_test_pair<"Random Test", false>(newer_string);
		all_passed &= execute_test_pair<"Twitter Test", false>(newer_string);

		benchmarksuite::file_handle::save_file(newer_string, base_path + "/" + current_path + ".md");
		std::cout << "Md Data: " << newer_string << std::endl;

		return static_cast<int32_t>(!all_passed);
	}
}