/*
	MIT License

	Copyright (c) 2026 Nihilai Collective Corp

	Permission is hereby granted, free of charge, to any person obtaining a copy of this
	software and associated documentation files (the "Software"), to deal in the Software
	without restriction, including without limitation the rights to use, copy, modify, merge,
	publish, distribute, sublicense, and/or sell copies of the Software, and to permit
	persons to whom the Software is furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all copies or
	substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
	INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
	PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
	FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
	OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.
*/
/// https://github.com/nihilai-collective/Json-Performance
#pragma once

#include "common.hpp"

namespace tests {

	static constexpr benchmarksuite::string_literal stage_name{ "Json-Performance: Correctness Validation" };

	inline std::string make_commit_row(std::string_view label, std::string_view org_repo, std::string_view commit) {
		std::string result;
		result.reserve(label.size() + org_repo.size() + commit.size() * 2 + 32);
		result += "| ";
		result += label;
		result += ": [";
		result += commit;
		result += "](https://github.com/";
		result += org_repo;
		result += "/commit/";
		result += commit;
		result += ")  \n";
		return result;
	}

	inline std::string make_section00(std::string_view os_id, std::string_view os_version, std::string_view compiler_id, std::string_view compiler_version) {
		std::string result;
		result.reserve(os_id.size() + os_version.size() + compiler_id.size() + compiler_version.size() + 128);
		result += "# Json-Performance\nPerformance profiling of JSON libraries (Compiled and run on ";
		result += os_id;
		result += " ";
		result += os_version;
		result += " using the ";
		result += compiler_id;
		result += " ";
		result += compiler_version;
		result += " compiler).  \n\nLatest Results: (";
		return result;
	}

	inline std::string make_section01() {
		std::string result;
		result.reserve(256);
		result += "#### Using the following commits:\n----\n";
		result += make_commit_row("Jsonifier", "nihilai-collective/Jsonifier", JSONIFIER_COMMIT);
		result += make_commit_row("Simdjson (On Demand)", "RealTimeChris/simdjson", SIMDJSON_COMMIT);
		return result;
	}

	std::string make_section02(std::string_view cpu_name, std::string_view jsonifier_cpu_name, std::string_view simdjson_cpu_name) {
		std::string stream;
		stream.reserve(512);
		stream += "\n#### Active Implementations:\n";
		stream += "| Library | Active Implementation |\n";
		stream += "| ------- | --------------------- |\n";
		stream += "| Jsonifier | `";
		stream += jsonifier_cpu_name;
		stream += "` |\n";
		stream += "| simdjson (ondemand) | `";
		stream += simdjson_cpu_name;
		stream += "` |\n";
		stream += "\n>> In these tests, we are comparing the 'json structural tape' generated by each of the libraries during their 'stage-1' parsing. You can view the branch "
				  "that was created on the simdjson repo to facilitate this comparison "
				  "[here](https://github.com/RealTimeChris/simdjson/commit/7002cd32).  \n\n";
		return stream;
	}

	struct comparison_context {
		std::vector<uint32_t> indices{};

		comparison_context() {
			indices.reserve(4096);
		}
	};

	template<benchmarksuite::string_literal test_name> bool execute_test(std::string& newer_string) {
		static constexpr std::string_view test_str{ test_name };
		std::string full_path;
		full_path.reserve(json_path.size() + 1 + test_str.size() + 5);
		full_path += std::string_view{ json_path };
		full_path += "/";
		full_path += test_str;
		full_path += ".json";
		auto json_data_in = benchmarksuite::file_handle::get(full_path);

		comparison_context jsonifier_context{};
		jsonifier::jsonifier_core<> jsonifier_parser{};
		jsonifier_parser.parseJsonForComparison<jsonifier::parse_options{ .partialRead = true }>(jsonifier_context, json_data_in);

		comparison_context simdjson_context{};
		simdjson::ondemand::parser simdjson_parser{};
		simdjson_parser.iterate_for_comparison(simdjson_context, simdjson::padded_string_view{ json_data_in });

		newer_string += "\n----\n### ";
		newer_string += test_str;
		newer_string += " Structural Comparison\n\n";

		if (jsonifier_context.indices.size() != simdjson_context.indices.size()) {
			std::cerr << "Count mismatch for " << test_str << ": Jsonifier=" << jsonifier_context.indices.size() << ", Simdjson=" << simdjson_context.indices.size() << std::endl;
			newer_string += "**MISMATCH:** Jsonifier produced ";
			newer_string += std::to_string(jsonifier_context.indices.size());
			newer_string += " structurals, Simdjson produced ";
			newer_string += std::to_string(simdjson_context.indices.size());
			newer_string += ".\n\n";
			return false;
		}

		auto [j_it, s_it] = std::mismatch(jsonifier_context.indices.begin(), jsonifier_context.indices.end(), simdjson_context.indices.begin());
		if (j_it != jsonifier_context.indices.end()) {
			auto idx = std::distance(jsonifier_context.indices.begin(), j_it);
			std::cerr << "Structural index mismatch in " << test_str << " at tape index " << idx << " (Jsonifier=" << *j_it << ", Simdjson=" << *s_it << ")" << std::endl;
			newer_string += "**MISMATCH:** Value divergence starting at index ";
			newer_string += std::to_string(idx);
			newer_string += ". ❌\n\n";
			return false;
		}

		std::cout << "All " << jsonifier_context.indices.size() << " structurals match for test: " << test_str << std::endl;
		newer_string += "All **";
		newer_string += std::to_string(jsonifier_context.indices.size());
		newer_string += "** structurals match between Jsonifier and Simdjson. ✅\n\n";
		return true;
	}

	inline int32_t test_function() {
		const std::string jsonifier_cpu_name{ jsonifier::cpu_arch_name };
		const std::string simdjson_cpu_name{ simdjson::get_active_implementation().operator*().name() };
		std::string newer_string{ make_section00(benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::os_id,
									  benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::os_version,
									  benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::compiler_id,
									  benchmarksuite::system_info_data<benchmarksuite::benchmark_types::cpu>::compiler_version) +
			benchmarksuite::get_time() + ")\n" + make_section01() +
			make_section02(benchmarksuite::internal::get_device_info<benchmarksuite::benchmark_types::cpu>(), jsonifier_cpu_name, simdjson_cpu_name) };
		newer_string.reserve(newer_string.size() + 26 * 512);

		bool all_passed = true;
		all_passed		= execute_test<"Abc Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Abc Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Apache Builds Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Apache Builds Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Canada Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Canada Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"CitmCatalog Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"CitmCatalog Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Discord Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Discord Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Github Events Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Github Events Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Google Maps Response Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Google Maps Response Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Instruments Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Instruments Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Marine IK Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Marine IK Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Mesh Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Mesh Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Random Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Random Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Semanticscholar Corpus Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Semanticscholar Corpus Test (Prettified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Twitter Test (Minified)">(newer_string) && all_passed;
		all_passed		= execute_test<"Twitter Test (Prettified)">(newer_string) && all_passed;

		benchmarksuite::file_handle::save_file(newer_string, base_path + "/" + current_path + ".md");
		std::cout << "Md Data: " << newer_string << std::endl;

		if (all_passed) {
			return 0;
		} else {
			return -1;
		}
	}
}